### ISSUE TITLE
`virtload-classic.sh` might be helpful

### ISSUE THREAD

**Issue by white-gecko** [Dockerizing/virtuoso-import-docker#2]
If we think we still need `virtload-classic.sh`, which might be helpful, we should somehow integrate it into `import.sh`.

**Comment by TBoonX** [comment]
`virtload-classic.sh` has 3 to 4 phases:

1. Unzip
2. Convert to n-triples
3. (optional) Split of large files
4. Load

Phase 1 seems to be needless regarding your comment in [Issue 1](https://github.com/Dockerizing/virtuoso-import-docker/issues/1)

Phase 2 could be reused and extended. `isql-v` needs n-triples or turtle files with a corresponding graph file plus a global graph file for all n-triple files which dont have a graph file. This situation should be checked and at least printed out for the user.

Phase 3 should be discussed, because in our script we could do parallel loading which helps also with big files. I propose to do the parallel loading and add splitting up large files later (conditionally 
 - if there a just a few big files then splitting them is great).

Phase 4 makes use of the `TTLP_MT` command which 
> Loads the TTL (TURTLE or N3 resource) file on multiple threads, using parallel I/O and multiprocessing if available.

This should be used in our script in order to reduce the number of queries we send to virtuoso.

**Comment by TBoonX** [comment]
I started coding but found issues with my assumptions:
The `TTLP_MT ` command could only use one file. Thus we keep our code for importing all the files at once. With this there is no need to transform the files to n-triples because bulk loading supports them all.

Thus there is nothing we could integrate in our script.

**Comment by white-gecko** [comment]
I think this is relevant for large files which are to big to be loaded with the `ld_dir()` method.

**Comment by white-gecko** [comment]
Because we don't have any use for it now, we leave it to the future.
Closed by d3d0707fc7d2fa5284546f10ee1c4c46f0ad9e7c.
